name: Mirror
on: push
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Mirror Action
        uses: https://github.com/pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@github.com:zvdxc/infoseitepagesmirror.git
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # If using SSH
          # OR use token-based auth in the URL as shown in the previous example